name: CI Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Write application-secret.yml to runner
        run: |
          echo "${{ secrets.APPLICATION_SECRET }}" > application-secret.yml

      - name: Move secret into resources
        run: |
          mkdir -p src/main/resources
          mv application-secret.yml src/main/resources/

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew clean build test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/assu-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/assu-app:latest
